agent_name: elcollectooorr
author: elcollectooorr
version: 0.1.0
license: Apache-2.0
description: El Collectooorr decentralized.
aea_version: '>=1.0.0, <2.0.0'
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
- valory/abci:0.1.0:bafybeiaau6gvge6gh5xp7brrpljqe3mhosy3p67e5cgivtypj7nplmii24
- valory/http_client:0.1.0:bafybeiajlo43jrfdhtkpagjtj4izm2rc24ysbnzbtxnu5qqc2pxoov66z4
- valory/ledger:0.1.0:bafybeiemp6u7xsyvwcq25i3t62oiykwsg5wmp7xs2e6eidll5vf3htdpwy
- valory/p2p_libp2p_client:0.1.0:bafybeigvayl4ykzqf6o6bw2irv7am3qvczjoeu7yjhzn27ajiwvcio3lxm
contracts:
- elcollectooorr/artblocks:0.1.0:bafybeibdgvtwjxi7rhjaubexpzw2od3zeahl7pfxbmvmyx4grat3vpzmmi
- elcollectooorr/artblocks_minter_filter:0.1.0:bafybeiehuqgzexwz7wlcitgoz6zgp4ks4reoazq5mc3sgvgeasmsuakjbq
- elcollectooorr/artblocks_periphery:0.1.0:bafybeicbkgpwb372na2j3khveekvdw4h34ohvpufixvuh2f4x6hdj7z52e
- elcollectooorr/basket:0.1.0:bafybeidssctakv7oorndux32xuu7rbnkeka3nm4pylyldkfww2xtuqvqiq
- elcollectooorr/basket_factory:0.1.0:bafybeihg43xlt66kwnwvymfwmml7d4zdh4j4m3wfnlakvz35q33wlam3ny
- elcollectooorr/token_vault:0.1.0:bafybeifysc2r7t5h32kvck4nkeyjccyqaq7ubjizlm2zashpag4p7lyvw4
- elcollectooorr/token_vault_factory:0.1.0:bafybeia37ppv5ogxtndcbt33ztbmer4zw7jhamlk64oqwziqdj6dnqoori
- valory/gnosis_safe:0.1.0:bafybeif5ump4p7p5bygqyxeznwdvtdhtwihxnjnvjajbcnt7rmcyzyjafy
- valory/gnosis_safe_proxy_factory:0.1.0:bafybeiffdg3dpuynvbw7vusdiuuqkgl4gxok6ezlgv3senji2ybnl6m2iy
- valory/multisend:0.1.0:bafybeidvuabdn32lpsh3z7wb5fonotimysfsntueeb53dgil5jmiezrasq
- valory/service_registry:0.1.0:bafybeidtwbj7mwiskbbmsw43zzooivuq6nripdzn7yuoou66rq7spom54m
protocols:
- open_aea/signing:1.0.0:bafybeid6f5ceool4evgaxdegs5pkjoivqjk3mo3ehctalswngb5m5c32wm
- valory/abci:0.1.0:bafybeianfguceeckwhelenmythqmbtqswll6vcaz5wwsdr7hin7ov3rvje
- valory/acn:1.1.0:bafybeidetrrkvdgveu4ph5g6v53lbh7ardfspbkpstmjxctx647bzyosyy
- valory/contract_api:1.0.0:bafybeigkedpmqhm7lrqusnkyfcapyx3dlkz2djfq74hou5pwtrskxgvuxu
- valory/http:1.0.0:bafybeienmids6f5pcey2bnywmiup2faawqgmdhhz65qfciuhkntugztvpi
- valory/ledger_api:1.0.0:bafybeif2c3jt4tim3zbfq5c2lds7bs6qj5gvj2obk3pzdk3uy6zk2ivo3e
- valory/tendermint:0.1.0:bafybeihcnjhovvyyfbkuw5sjyfx2lfd4soeocfqzxz54g67333m6nk5gxq
skills:
- elcollectooorr/elcollectooorr_abci:0.1.0:bafybeihtxuow7odhx4ysrznppuvm3tdyiwnlehs3c7ch4qgbkaarxd2xny
- elcollectooorr/fractionalize_deployment_abci:0.1.0:bafybeigb5koyqokbxrcd5pgtqfz4dzr4tgra4oto4dfxvjpqokyz7ufpwi
- valory/abstract_abci:0.1.0:bafybeiam52ztcss46i3tgywuv4qmvddqgn7exmbt5kcicqpyip4kfeyap4
- valory/abstract_round_abci:0.1.0:bafybeify5cyzxqczuoap2winsssau5wjiv4nhvla7ktmamhadsq5x2p6si
- valory/registration_abci:0.1.0:bafybeihebvuim7u5wkkzbj6bseywo27eudezdcvmbi33swejasd6mvjkmi
- valory/reset_pause_abci:0.1.0:bafybeidjcxhhywaa5ddaqh7jikbxqk4qdcmt2sxhpx3eib5o6ji4xyywsq
- valory/safe_deployment_abci:0.1.0:bafybeifmod3ndokxqaziurgvg7ht672hfvajj2azdvsimqfakeobxhvny4
- valory/transaction_settlement_abci:0.1.0:bafybeidooww4lrevaihswxe4tlbzsixlcmqdznn7we2ep5k2brt4j5tmq4
default_ledger: ethereum
required_ledgers:
- ethereum
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  version: 1
  disable_existing_loggers: false
  formatters:
    standard:
      format: '[%(asctime)s] [%(levelname)s] %(message)s'
  handlers:
    logfile:
      class: logging.FileHandler
      formatter: standard
      filename: ${LOG_FILE:str:log.txt}
      level: INFO
    console:
      class: logging.StreamHandler
      formatter: standard
      stream: ext://sys.stdout
  loggers:
    aea:
      handlers:
      - logfile
      - console
      propagate: false
dependencies:
  open-aea-ledger-ethereum: {}
default_connection: null
---
public_id: valory/abci:0.1.0
type: connection
config:
  target_skill_id: elcollectooorr/elcollectooorr_abci:0.1.0
  host: ${ABCI_HOST:str:localhost}
  port: ${ABCI_PORT:int:26658}
  use_tendermint: ${ABCI_USE_TENDERMINT:bool:false}
---
public_id: valory/p2p_libp2p_client:0.1.0
type: connection
config:
  nodes:
  - uri: ${P2P_URI:str:acn.staging.autonolas.tech:9005}
    public_key: ${P2P_PUBLIC_KEY:str:0250827315351f6f4d3777b77d4bfd67280156240313bf221750b36404344bb35d}
cert_requests:
- identifier: acn
  ledger_id: ethereum
  message_format: '{public_key}'
  not_after: '2022-01-01'
  not_before: '2021-01-01'
  public_key: ${P2P_PUBLIC_KEY:str:0250827315351f6f4d3777b77d4bfd67280156240313bf221750b36404344bb35d}
  save_path: .certs/acn_cosmos_9005.txt
is_abstract: true
---
public_id: elcollectooorr/elcollectooorr_abci:0.1.0
type: skill
models:
  params:
    args:
      artblocks_contract: '0xa7d8d9ef8D8Ce8992Df33D8b8CF4Aebabd5bD270'
      artblocks_graph_url: https://api.thegraph.com/subgraphs/name/artblocks/art-blocks
      artblocks_minter_filter: '0x4aafce293b9b0fad169c78049a81e400f518e199'
      basket_factory_address: '0xde771104C0C44123d22D39bB716339cD0c3333a1'
      budget_per_vault: 10500000000000000000
      cleanup_history_depth: 1
      consensus:
        max_participants: ${SKILL_ELCOLLECTOOORR_ABCI_MODELS_PARAMS_ARGS_CONSENSUS_MAX_PARTICIPANTS:int:1}
      decision_model_threshold: ${SKILL_ELCOLLECTOOORR_ABCI_MODELS_PARAMS_ARGS_DECISION_MODEL_THRESHOLD:float:0.0}
      setup:
        safe_contract_address: ${SKILL_ELCOLLECTOOORR_ABCI_MODELS_PARAMS_ARGS_SETUP_SAFE_CONTRACT_ADDRESS:list:[]}
      decision_model_type: 'yes'
      drand_public_key: 868f005eb8e6e4ca0a47c8a77ceaa5309a47978a7c71bc5cce96366b5d7a569937c529eeda66c7293784a9402801af31
      enforce_investor_whitelisting: true
      finalize_timeout: 60.0
      history_check_timeout: 1205
      keeper_allowed_retries: 3
      keeper_timeout: 30.0
      max_healthcheck: 120
      max_purchase_per_project: 1
      max_retries: 5
      multisend_address: '0xA238CBeb142c10Ef7Ad8442C6D1f9E89e07e7761'
      observation_interval: 10
      on_chain_service_id: null
      reset_tendermint_after: 2
      retry_attempts: 400
      retry_timeout: 3
      round_timeout_seconds: 120.0
      service_id: el_collectooorr_1
      service_registry_address: null
      settings_address: '0xE0FC79183a22106229B84ECDd55cA017A07eddCa'
      sleep_time: 1
      starting_project_id: 301
      tendermint_check_sleep_delay: 3
      tendermint_max_retries: 5
      tendermint_url: ${TENDERMINT_URL:str:http://localhost:26657}
      tendermint_com_url: ${TENDERMINT_COM_URL:str:http://localhost:8080}
      token_vault_factory_address: '0x85Aa7f78BdB2DE8F3e0c0010d99AD5853fFcfC63'
      validate_timeout: 1205
      wei_to_fraction: 10500000000000000
      whitelisted_investor_addresses: ${SKILL_ELCOLLECTOOORR_ABCI_MODELS_PARAMS_ARGS_WHITELISTED_INVESTOR_ADDRESSES:list:[]}
---
public_id: valory/ledger:0.1.0
type: connection
config:
  ledger_apis:
    ethereum:
      address: ${LEDGER_ADDRESS:str:http://localhost:8545}
      chain_id: ${LEDGER_CHAIN_ID:int:31337}
      poa_chain: ${LEDGER_POA_CHAIN:bool:false}
      default_gas_price_strategy: ${LEDGER_DEFAULT_GAS_PRICE_STRATEGY:str:eip1559}
