agent_name: elcollectooorr
author: elcollectooorr
version: 0.1.0
license: Apache-2.0
description: El Collectooorr decentralized.
aea_version: '>=1.0.0, <2.0.0'
fingerprint:
  __init__.py: bafybeidulnstm63bgmfo34rd74xqcvf36o7ly7w7s4bylr4afbclnogn6q
  tests/__init__.py: bafybeiek3wepzhlahicjtjqrnxg7zis5cdy4y6ixemjklisocxtbgnpkqm
  tests/conftest.py: bafybeig5kczh6oi6lzdvug4ost2konoox75ki4jymeujsjozzqctqhngwa
  tests/data/json_server/data.json: bafybeibg6rfceitizdby4o2dhvpnlc64tdeustfxawliodviomrdltqrg4
  tests/fixture_helpers.py: bafybeiftrapue6wb6dv6wfsdhuaxc2prn6fzltcdbrynnvbpvyqkzzvyau
  tests/helpers/__init__.py: bafybeifzu3wezqxxzwznjug3xwqlumu76fmdvj7aiywutqgrakbxzimu3i
  tests/helpers/artblocks_utils.py: bafybeibcyv4mp5xrkepsqlhgq5okz2hbjlose6w6wra75exhoxzcbdfkbi
  tests/helpers/constants.py: bafybeidzusrogrrpltcvbth6t7ceuhzkotcj6aqy77ew3mnxsd6midntcm
  tests/helpers/docker/__init__.py: bafybeidakk3cxongkwm6pkuokufzpqr2ms2fvnecmdpxdm5lk7d2ko244q
  tests/helpers/docker/elcol_net.py: bafybeia3rzjwwc3isxqnzh6b33lf2m3psuzxj4jlrx7zwomzctxzy6sqoy
  tests/helpers/docker/mock_arblocks_api.py: bafybeid2mp277jhtjnd5piy3eeyc2hghp7mgfu6k2agwohvgi7fvhmhx2a
  tests/helpers/hardhat/Dockerfile: bafybeih7wleg3g263gfsimckqgqb5rtpd72uwm4wzhba2v5u5es5gqhkwy
  tests/helpers/hardhat/hardhat.config.js: bafybeiag3rxhb2luzd4nr6whsti7wtlnvzlm32gctq45p6xfwmsyijpe54
  tests/helpers/hardhat/package.json: bafybeifjyofuzq66sjjtxdynvy4be5rxzkiuwyntjibrjvsrly5ddeai64
  tests/test_agents/__init__.py: bafybeifocm5xbm4nryrzkmzot4bzfnrcnc7nggepgsywterkgw4f44awfi
  tests/test_agents/base_elcollectooorr.py: bafybeiefd5ojyjvujjitygp5s5z6eryi7fbfikhsu27fqqtx6up6dmaoyi
  tests/test_agents/test_elcollectooorr_abci.py: bafybeiecsznoutrwxoftf4iu2sesezfxuyzvpyahsv5wnl54hb5xvsp5wa
  tests/test_fractionalize_deployment_abci/__init__.py: bafybeifpwsaub3khxsixvj6yc2b7zlmkpt3h6m2q65x2zmmo6uvcbpdgpm
  tests/test_fractionalize_deployment_abci/test_behaviours.py: bafybeie5xi22lae6wkkrarqdvmigc5quxx7ocq67h4dt2mi7bal4fy4zum
  tests/test_fractionalize_deployment_abci/test_dialogues.py: bafybeihea5tjndkyr2a5ezys26mxw3bcrsyrhqdd75egux35ydtvadndva
  tests/test_fractionalize_deployment_abci/test_payloads.py: bafybeidmsyb6ejirhr3o4f7yflxp54mnbhjp64rwbcd2oyu7wcz4pxvsh4
  tests/test_fractionalize_deployment_abci/test_rounds.py: bafybeidje5lpztfu5vcknpfhrj4n5l65oasf56c6gorou2xhapostupgha
  tests/test_token_vault/__init__.py: bafybeiav66mysea6p62i7hg4vukzqgxp2khzftxxhjyjlq34fzkjyvbaba
  tests/test_token_vault/test_contract.py: bafybeifbgxr5pclftalkyzz7cyauiq7kqxdvsipacgq65yjuvpry32etjq
  tests/test_token_vault_factory/__init__.py: bafybeibvzzcxfah75gtx6wlvc6k2lfsbwo572bltjxwg2orlv3oqhj5yrq
  tests/test_token_vault_factory/test_contract.py: bafybeibpcizflmxkpi4ik7pnqwxhzjxrin2hret55lvrikigqhv5ptr3dm
fingerprint_ignore_patterns: []
connections:
- valory/http_server:0.22.0:bafybeihpgu56ovmq4npazdbh6y6ru5i7zuv6wvdglpxavsckyih56smu7m
- valory/abci:0.1.0:bafybeibnomg7hzcco23lbwhnoh7uel3odiv4tvbtndp5ads3szdrlcl2wy
- valory/http_client:0.23.0:bafybeih5vzo22p2umhqo52nzluaanxx7kejvvpcpdsrdymckkyvmsim6gm
- valory/ipfs:0.1.0:bafybeieobovka44gjw5pqbypmtrxmqklojzw7v5jsacoqxvpp2imsyd53y
- valory/ledger:0.19.0:bafybeic3ft7l7ca3qgnderm4xupsfmyoihgi27ukotnz7b5hdczla2enya
- valory/p2p_libp2p_client:0.1.0:bafybeid3xg5k2ol5adflqloy75ibgljmol6xsvzvezebsg7oudxeeolz7e
contracts:
- elcollectooorr/artblocks:0.1.0:bafybeidddkxscvadugcdmlexny5rnaekphkzxpuei2r2euxxa4tqzih5lq
- elcollectooorr/artblocks_minter_filter:0.1.0:bafybeiaax6ehgjtw5mpezpbkjyllsyendi6cky7isdcofjiwl65obutpta
- elcollectooorr/artblocks_periphery:0.1.0:bafybeihwebyh235tybahv5omde6auflwrqfmquxkpbtjmw4ozfxffip54u
- elcollectooorr/basket:0.1.0:bafybeihwsbk36p7kpanylozuad3hd3emjwlby3qfxicacattmrzg6c5pra
- elcollectooorr/basket_factory:0.1.0:bafybeihql7n4nqxjkg6b4nq33j3wn7yn6xatmmgu26ljtlse3mlf7ce35y
- elcollectooorr/token_vault:0.1.0:bafybeidttmtr7khtejsg63jeze75am3jhlrnh42kck6jymiswgezbny7w4
- elcollectooorr/token_vault_factory:0.1.0:bafybeifknhf35ojcybg3ddj2uv6qo3ikibab7fultuk5tu7safxunmq43a
- valory/gnosis_safe:0.1.0:bafybeia2m32xfpsddrww7j3unkhcijuitlixffg66igrdyt6kgh5jvvwum
- valory/gnosis_safe_proxy_factory:0.1.0:bafybeien67v6nu5btupwmekr7feyggu6u3nqo5unzsg25xlias6pmgz7ee
- valory/multicall2:0.1.0:bafybeigi47jlga5dsv7ew332ukccxnmbez5nqnkpbyqmm366llrvjxua4i
- valory/multisend:0.1.0:bafybeig5byt5urg2d2bsecufxe5ql7f4mezg3mekfleeh32nmuusx66p4y
- valory/service_registry:0.1.0:bafybeiew6yobxk5jd4yct7z5tlsuobryymedj6vz7t74hmjo5llahahsxi
protocols:
- open_aea/signing:1.0.0:bafybeihv62fim3wl2bayavfcg3u5e5cxu3b7brtu4cn5xoxd6lqwachasi
- valory/abci:0.1.0:bafybeiaqmp7kocbfdboksayeqhkbrynvlfzsx4uy4x6nohywnmaig4an7u
- valory/acn:1.1.0:bafybeidluaoeakae3exseupaea4i3yvvk5vivyt227xshjlffywwxzcxqe
- valory/contract_api:1.0.0:bafybeidgu7o5llh26xp3u3ebq3yluull5lupiyeu6iooi2xyymdrgnzq5i
- valory/http:1.0.0:bafybeifugzl63kfdmwrxwphrnrhj7bn6iruxieme3a4ntzejf6kmtuwmae
- valory/ipfs:0.1.0:bafybeiftxi2qhreewgsc5wevogi7yc5g6hbcbo4uiuaibauhv3nhfcdtvm
- valory/ledger_api:1.0.0:bafybeihdk6psr4guxmbcrc26jr2cbgzpd5aljkqvpwo64bvaz7tdti2oni
- valory/tendermint:0.1.0:bafybeig4mi3vmlv5zpbjbfuzcgida6j5f2nhrpedxicmrrfjweqc5r7cra
skills:
- elcollectooorr/elcollectooorr_abci:0.1.0:bafybeidit22bsl3rmau7rxitwtr4os3cmudwk43jijq2it66t2nyglk4e4
- elcollectooorr/fractionalize_deployment_abci:0.1.0:bafybeiejywuarc2q5wlyzijdvxtfoa42u6nqkfaoogkqdicv4nitz25dwe
- valory/abstract_abci:0.1.0:bafybeidbrzxykkdplynsh2z6iskqq26le2t4yvog4expn5v6g2iyyd7clq
- valory/abstract_round_abci:0.1.0:bafybeib3te5ami7gi7vh6v2rvq7mjmatyqdzqwkqpn7qh6mzfmpc4ikq4q
- valory/registration_abci:0.1.0:bafybeigeferybxvqw4fl2cu2mcmfhfpxdruw3jtsswlmvhag3pav47ia5e
- valory/reset_pause_abci:0.1.0:bafybeig2fb6i66uq5g3kzcd32rmv4z4xqjsslteqpz44adwxjd6op54uxq
- valory/termination_abci:0.1.0:bafybeihn5gc2uf7gnnjwwpgbgvbcivhac7hgzq54zlr4mj3vmsblhl2fna
- valory/transaction_settlement_abci:0.1.0:bafybeib4qqbpcdbfba23jm4c3ki7imo4wn5wtsja3tqrsrdlulh3lnixby
default_ledger: ethereum
required_ledgers:
- ethereum
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  version: 1
  disable_existing_loggers: false
  formatters:
    standard:
      format: '[%(asctime)s] [%(levelname)s] %(message)s'
  handlers:
    logfile:
      class: logging.FileHandler
      formatter: standard
      filename: ${LOG_FILE:str:log.txt}
      level: INFO
    console:
      class: logging.StreamHandler
      formatter: standard
      stream: ext://sys.stdout
  loggers:
    aea:
      handlers:
      - logfile
      - console
      propagate: false
dependencies:
  open-aea-ledger-ethereum:
    version: ==1.47.0
default_connection: null
---
public_id: valory/abci:0.1.0
type: connection
config:
  target_skill_id: elcollectooorr/elcollectooorr_abci:0.1.0
  host: ${str:localhost}
  port: ${int:26658}
  use_tendermint: ${bool:false}
---
public_id: valory/p2p_libp2p_client:0.1.0
type: connection
config:
  nodes:
  - uri: ${str:acn.staging.autonolas.tech:9005}
    public_key: ${str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
cert_requests:
- identifier: acn
  ledger_id: ethereum
  message_format: '{public_key}'
  not_after: '2023-01-01'
  not_before: '2022-01-01'
  public_key: ${str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
  save_path: .certs/acn_cosmos_11000.txt
---
public_id: elcollectooorr/elcollectooorr_abci:0.1.0
type: skill
models:
  params:
    args:
      artblocks_contract: '0xa7d8d9ef8D8Ce8992Df33D8b8CF4Aebabd5bD270'
      artblocks_graph_url: https://api.thegraph.com/subgraphs/name/artblocks/art-blocks
      artblocks_minter_filter: '0x4aafce293b9b0fad169c78049a81e400f518e199'
      basket_factory_address: '0xde771104C0C44123d22D39bB716339cD0c3333a1'
      budget_per_vault: 10500000000000000000
      cleanup_history_depth: 1
      decision_model_threshold: ${float:0.0}
      setup:
        safe_contract_address: ${str:null}
        all_participants: ${list:[]}
        consensus_threshold: ${int:null}
      decision_model_type: 'yes'
      drand_public_key: 868f005eb8e6e4ca0a47c8a77ceaa5309a47978a7c71bc5cce96366b5d7a569937c529eeda66c7293784a9402801af31
      enforce_investor_whitelisting: true
      finalize_timeout: 60.0
      history_check_timeout: 1205
      keeper_allowed_retries: 3
      keeper_timeout: 30.0
      max_healthcheck: 120
      max_purchase_per_project: 1
      max_retries: 5
      multisend_address: '0xA238CBeb142c10Ef7Ad8442C6D1f9E89e07e7761'
      reset_pause_duration: 300
      on_chain_service_id: ${int:1}
      reset_tendermint_after: 60
      retry_attempts: 400
      retry_timeout: 3
      round_timeout_seconds: 120.0
      service_id: el_collectooorr_1
      multicall_batch_size: ${int:50}
      service_registry_address: ${str:0x48b6af7B12C71f09e2fC8aF4855De4Ff54e775cA}
      settings_address: '0xE0FC79183a22106229B84ECDd55cA017A07eddCa'
      sleep_time: ${int:1}
      starting_project_id: 301
      share_tm_config_on_startup: ${bool:false}
      tendermint_check_sleep_delay: 3
      tendermint_max_retries: 5
      tendermint_url: ${str:http://localhost:26657}
      tendermint_p2p_url: ${str:localhost:26656}
      tendermint_com_url: ${str:http://localhost:8080}
      token_vault_factory_address: '0x85Aa7f78BdB2DE8F3e0c0010d99AD5853fFcfC63'
      use_termination: ${bool:false}
      validate_timeout: 1205
      wei_to_fraction: 10500000000000000
      whitelisted_investor_addresses: ${list:[]}
      service_endpoint_base: ${str:https://dummy_service.autonolas.tech/}
      use_slashing: ${bool:false}
      slash_cooldown_hours: ${int:3}
      slash_threshold_amount: ${int:10000000000000000}
      light_slash_unit_amount: ${int:5000000000000000}
      serious_slash_unit_amount: ${int:8000000000000000}
      termination_from_block: ${int:0}
---
public_id: valory/ledger:0.19.0
type: connection
config:
  ledger_apis:
    ethereum:
      address: ${str:http://localhost:8545}
      chain_id: ${int:31337}
      poa_chain: ${bool:false}
      default_gas_price_strategy: ${str:eip1559}
---
public_id: valory/http_server:0.22.0:bafybeicblltx7ha3ulthg7bzfccuqqyjmihhrvfeztlgrlcoxhr7kf6nbq
type: connection
config:
  host: 0.0.0.0
  target_skill_id: elcollectooorr/elcollectooorr_abci:0.1.0
