agent_name: elcollectooorr
author: elcollectooorr
version: 0.1.0
license: Apache-2.0
description: El Collectooorr decentralized.
aea_version: '>=1.0.0, <2.0.0'
fingerprint:
  __init__.py: bafybeidulnstm63bgmfo34rd74xqcvf36o7ly7w7s4bylr4afbclnogn6q
  tests/__init__.py: bafybeiek3wepzhlahicjtjqrnxg7zis5cdy4y6ixemjklisocxtbgnpkqm
  tests/conftest.py: bafybeig5kczh6oi6lzdvug4ost2konoox75ki4jymeujsjozzqctqhngwa
  tests/data/json_server/data.json: bafybeibg6rfceitizdby4o2dhvpnlc64tdeustfxawliodviomrdltqrg4
  tests/fixture_helpers.py: bafybeiftrapue6wb6dv6wfsdhuaxc2prn6fzltcdbrynnvbpvyqkzzvyau
  tests/helpers/__init__.py: bafybeifzu3wezqxxzwznjug3xwqlumu76fmdvj7aiywutqgrakbxzimu3i
  tests/helpers/artblocks_utils.py: bafybeibcyv4mp5xrkepsqlhgq5okz2hbjlose6w6wra75exhoxzcbdfkbi
  tests/helpers/constants.py: bafybeidzusrogrrpltcvbth6t7ceuhzkotcj6aqy77ew3mnxsd6midntcm
  tests/helpers/docker/__init__.py: bafybeidakk3cxongkwm6pkuokufzpqr2ms2fvnecmdpxdm5lk7d2ko244q
  tests/helpers/docker/elcol_net.py: bafybeia3rzjwwc3isxqnzh6b33lf2m3psuzxj4jlrx7zwomzctxzy6sqoy
  tests/helpers/docker/mock_arblocks_api.py: bafybeid2mp277jhtjnd5piy3eeyc2hghp7mgfu6k2agwohvgi7fvhmhx2a
  tests/helpers/hardhat/Dockerfile: bafybeih7wleg3g263gfsimckqgqb5rtpd72uwm4wzhba2v5u5es5gqhkwy
  tests/helpers/hardhat/hardhat.config.js: bafybeiag3rxhb2luzd4nr6whsti7wtlnvzlm32gctq45p6xfwmsyijpe54
  tests/helpers/hardhat/package.json: bafybeifjyofuzq66sjjtxdynvy4be5rxzkiuwyntjibrjvsrly5ddeai64
  tests/test_agents/__init__.py: bafybeifocm5xbm4nryrzkmzot4bzfnrcnc7nggepgsywterkgw4f44awfi
  tests/test_agents/base_elcollectooorr.py: bafybeiefd5ojyjvujjitygp5s5z6eryi7fbfikhsu27fqqtx6up6dmaoyi
  tests/test_agents/test_elcollectooorr_abci.py: bafybeiecsznoutrwxoftf4iu2sesezfxuyzvpyahsv5wnl54hb5xvsp5wa
  tests/test_fractionalize_deployment_abci/__init__.py: bafybeifpwsaub3khxsixvj6yc2b7zlmkpt3h6m2q65x2zmmo6uvcbpdgpm
  tests/test_fractionalize_deployment_abci/test_behaviours.py: bafybeid74vtqghw3uykuufsso5xxtin57v7s4d2p4euxqyiw7q4cop5qqy
  tests/test_fractionalize_deployment_abci/test_dialogues.py: bafybeihea5tjndkyr2a5ezys26mxw3bcrsyrhqdd75egux35ydtvadndva
  tests/test_fractionalize_deployment_abci/test_payloads.py: bafybeidmsyb6ejirhr3o4f7yflxp54mnbhjp64rwbcd2oyu7wcz4pxvsh4
  tests/test_fractionalize_deployment_abci/test_rounds.py: bafybeie673kjeejmeenvy6figj6pdhlhdvtlppxkilrih6ro5viw4chn6q
  tests/test_token_vault/__init__.py: bafybeiav66mysea6p62i7hg4vukzqgxp2khzftxxhjyjlq34fzkjyvbaba
  tests/test_token_vault/test_contract.py: bafybeifbgxr5pclftalkyzz7cyauiq7kqxdvsipacgq65yjuvpry32etjq
  tests/test_token_vault_factory/__init__.py: bafybeibvzzcxfah75gtx6wlvc6k2lfsbwo572bltjxwg2orlv3oqhj5yrq
  tests/test_token_vault_factory/test_contract.py: bafybeibpcizflmxkpi4ik7pnqwxhzjxrin2hret55lvrikigqhv5ptr3dm
fingerprint_ignore_patterns: []
connections:
- valory/abci:0.1.0:bafybeihczvjnki5kxhyixkh4lxuxkqsuhqmpn63tneyj76p7cmgaxqo7pu
- valory/http_client:0.23.0:bafybeieoeuy4brzimtnubmokwirhrx27ezls6cdnl5qik4rkykfle3nn2y
- valory/ipfs:0.1.0:bafybeihr5kvz2oj4uxpiqcbjwfx5hpftm4drubugwcabdcht4gpna3l6ja
- valory/ledger:0.19.0:bafybeigfoz7d7si7s4jehvloq2zmiiocpbxcaathl3bxkyarxoerxq7g3a
- valory/p2p_libp2p_client:0.1.0:bafybeihdnfdth3qgltefgrem7xyi4b3ejzaz67xglm2hbma2rfvpl2annq
contracts:
- elcollectooorr/artblocks:0.1.0:bafybeifdyj3eqy65smqscqqbsamr4q6e4ebfs3jj54au6tw3gezqqrz4zm
- elcollectooorr/artblocks_minter_filter:0.1.0:bafybeicanahpmwfcglreyxwgpb6utvsknia7dgcqrtz4giqxyejopla4vm
- elcollectooorr/artblocks_periphery:0.1.0:bafybeieugvwntqpyelm22v6grzaxjv6ijaw6nq3elhuzvarv3exjmlqebe
- elcollectooorr/basket:0.1.0:bafybeiacdg2lvo7yq3phse44vbncvfw4mj2kkwuvdbndxtuvg7bucnhp3e
- elcollectooorr/basket_factory:0.1.0:bafybeiaulnlpxjikrzdehhp6tnogzajscip36t7ftlpvadiem2o47labn4
- elcollectooorr/token_vault:0.1.0:bafybeihm5352dvty56cnpa2d24aejm5rkky2236ncsncakarnw5p4334ee
- elcollectooorr/token_vault_factory:0.1.0:bafybeidxm4elfgl4omf6wlaevvcuyrkmpst3k3klonmp7foubsx2x7cmea
- valory/gnosis_safe:0.1.0:bafybeigaeon5qhgdwhduw4wtjt7x7o3hpz62aifr5a7522ynll3nps3qnm
- valory/gnosis_safe_proxy_factory:0.1.0:bafybeihuyxtxqp5f5sviid5hgtpuncd545hiurp3pjdbhqbs3u4kag4a2a
- valory/multicall2:0.1.0:bafybeiffhnnk3ibb3z53jxg4rfwcgjl657f56v3ld4rgafgavxxys3h74y
- valory/multisend:0.1.0:bafybeiemglycsigpsf2f6ohfdlsha7w6lrc5nmhlydmocna4apa7b4cqcq
- valory/service_registry:0.1.0:bafybeihi2tfcf4l7j6tzwb6vptrctkj57zye2oqxmyfwxc4u7gb2v3fmwa
protocols:
- open_aea/signing:1.0.0:bafybeifuxs7gdg2okbn7uofymenjlmnih2wxwkym44lsgwmklgwuckxm2m
- valory/abci:0.1.0:bafybeigootsvqpk6th5xpdtzanxum3earifrrezfyhylfrit7yvqdrtgpe
- valory/acn:1.1.0:bafybeiapa5ilsobggnspoqhspftwolrx52udrwmaxdxgrk26heuvl4oooa
- valory/contract_api:1.0.0:bafybeiasywsvax45qmugus5kxogejj66c5taen27h4voriodz7rgushtqa
- valory/http:1.0.0:bafybeia5bxdua2i6chw6pg47bvoljzcpuqxzy4rdrorbdmcbnwmnfdobtu
- valory/ipfs:0.1.0:bafybeibjzhsengtxfofqpxy6syamplevp35obemwfp4c5lhag3v2bvgysa
- valory/ledger_api:1.0.0:bafybeigsvceac33asd6ecbqev34meyyjwu3rangenv6xp5rkxyz4krvcby
- valory/tendermint:0.1.0:bafybeidjqmwvgi4rqgp65tbkhmi45fwn2odr5ecezw6q47hwitsgyw4jpa
skills:
- elcollectooorr/elcollectooorr_abci:0.1.0:bafybeiflxuycml6g3d7bgo2bwbvonbn4oyfe44f67c2fphrqrb7ttb6quq
- elcollectooorr/fractionalize_deployment_abci:0.1.0:bafybeiclvd7kd2hykcczujbijaqtc6qpnnbodryom5dcm2miwkeofl5j74
- valory/abstract_abci:0.1.0:bafybeibcemiz3qxoordadxwkxkjp7g7rerbfwap6wqxiepcms22ocb3v7i
- valory/abstract_round_abci:0.1.0:bafybeicyy4g3x6ol6x2ayzcdkg2wstubqecp6ycgo6f2c2bhjnhwdjs3qa
- valory/registration_abci:0.1.0:bafybeigexg5mw5sh35qkhlaeegycgtkd2ym5o4marjc5o7gl7t352hohiu
- valory/reset_pause_abci:0.1.0:bafybeigabcdz5en52zuxzxa6a4p5c7z4qyi3fcfp7lodqusjh32z5obcqy
- valory/termination_abci:0.1.0:bafybeies2zrbcsajnsgjq2ljr352gzvjsvkoycu65tuj5avnxlgjqlevci
- valory/transaction_settlement_abci:0.1.0:bafybeic7vatd3um6en3fqdxpbdsdq4n2zdqf3c4m5cs2r73ag5pbgdohoe
default_ledger: ethereum
required_ledgers:
- ethereum
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  version: 1
  disable_existing_loggers: false
  formatters:
    standard:
      format: '[%(asctime)s] [%(levelname)s] %(message)s'
  handlers:
    logfile:
      class: logging.FileHandler
      formatter: standard
      filename: ${LOG_FILE:str:log.txt}
      level: INFO
    console:
      class: logging.StreamHandler
      formatter: standard
      stream: ext://sys.stdout
  loggers:
    aea:
      handlers:
      - logfile
      - console
      propagate: false
dependencies:
  open-aea-ledger-ethereum: {}
default_connection: null
---
public_id: valory/abci:0.1.0
type: connection
config:
  target_skill_id: elcollectooorr/elcollectooorr_abci:0.1.0
  host: ${str:localhost}
  port: ${int:26658}
  use_tendermint: ${bool:false}
---
public_id: valory/p2p_libp2p_client:0.1.0
type: connection
config:
  nodes:
  - uri: ${str:acn.staging.autonolas.tech:9005}
    public_key: ${str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
cert_requests:
- identifier: acn
  ledger_id: ethereum
  message_format: '{public_key}'
  not_after: '2023-01-01'
  not_before: '2022-01-01'
  public_key: ${str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
  save_path: .certs/acn_cosmos_11000.txt
---
public_id: elcollectooorr/elcollectooorr_abci:0.1.0
type: skill
models:
  params:
    args:
      artblocks_contract: '0xa7d8d9ef8D8Ce8992Df33D8b8CF4Aebabd5bD270'
      artblocks_graph_url: https://api.thegraph.com/subgraphs/name/artblocks/art-blocks
      artblocks_minter_filter: '0x4aafce293b9b0fad169c78049a81e400f518e199'
      basket_factory_address: '0xde771104C0C44123d22D39bB716339cD0c3333a1'
      budget_per_vault: 10500000000000000000
      cleanup_history_depth: 1
      decision_model_threshold: ${float:0.0}
      setup:
        safe_contract_address: ${str:null}
        all_participants: ${list:[]}
        consensus_threshold: ${int:null}
      decision_model_type: 'yes'
      drand_public_key: 868f005eb8e6e4ca0a47c8a77ceaa5309a47978a7c71bc5cce96366b5d7a569937c529eeda66c7293784a9402801af31
      enforce_investor_whitelisting: true
      finalize_timeout: 60.0
      history_check_timeout: 1205
      keeper_allowed_retries: 3
      keeper_timeout: 30.0
      max_healthcheck: 120
      max_purchase_per_project: 1
      max_retries: 5
      multisend_address: '0xA238CBeb142c10Ef7Ad8442C6D1f9E89e07e7761'
      reset_pause_duration: 300
      on_chain_service_id: ${int:1}
      reset_tendermint_after: 60
      retry_attempts: 400
      retry_timeout: 3
      round_timeout_seconds: 120.0
      service_id: el_collectooorr_1
      multicall_batch_size: ${int:50}
      service_registry_address: ${str:0x48b6af7B12C71f09e2fC8aF4855De4Ff54e775cA}
      settings_address: '0xE0FC79183a22106229B84ECDd55cA017A07eddCa'
      sleep_time: 1
      starting_project_id: 301
      share_tm_config_on_startup: ${bool:false}
      tendermint_check_sleep_delay: 3
      tendermint_max_retries: 5
      tendermint_url: ${str:http://localhost:26657}
      tendermint_p2p_url: ${str:localhost:26656}
      tendermint_com_url: ${str:http://localhost:8080}
      token_vault_factory_address: '0x85Aa7f78BdB2DE8F3e0c0010d99AD5853fFcfC63'
      use_termination: ${bool:false}
      validate_timeout: 1205
      wei_to_fraction: 10500000000000000
      whitelisted_investor_addresses: ${list:[]}
---
public_id: valory/ledger:0.19.0
type: connection
config:
  ledger_apis:
    ethereum:
      address: ${str:http://localhost:8545}
      chain_id: ${int:31337}
      poa_chain: ${bool:false}
      default_gas_price_strategy: ${str:eip1559}
