agent_name: elcollectooorr
author: elcollectooorr
version: 0.1.0
license: Apache-2.0
description: El Collectooorr decentralized.
aea_version: '>=1.0.0, <2.0.0'
fingerprint:
  __init__.py: bafybeidulnstm63bgmfo34rd74xqcvf36o7ly7w7s4bylr4afbclnogn6q
  tests/__init__.py: bafybeiek3wepzhlahicjtjqrnxg7zis5cdy4y6ixemjklisocxtbgnpkqm
  tests/conftest.py: bafybeihrv4kjnm653qlwocnbv66y7ufxipvsihpzgpdjyx76dx3qjpsdtm
  tests/data/json_server/data.json: bafybeibg6rfceitizdby4o2dhvpnlc64tdeustfxawliodviomrdltqrg4
  tests/fixture_helpers.py: bafybeiftrapue6wb6dv6wfsdhuaxc2prn6fzltcdbrynnvbpvyqkzzvyau
  tests/helpers/__init__.py: bafybeifzu3wezqxxzwznjug3xwqlumu76fmdvj7aiywutqgrakbxzimu3i
  tests/helpers/artblocks_utils.py: bafybeid7gcxt7t42oc5k74ddpx5cpyciwkfegmjrdcbrcfoqq3c4wxfquy
  tests/helpers/constants.py: bafybeidzusrogrrpltcvbth6t7ceuhzkotcj6aqy77ew3mnxsd6midntcm
  tests/helpers/docker/__init__.py: bafybeidakk3cxongkwm6pkuokufzpqr2ms2fvnecmdpxdm5lk7d2ko244q
  tests/helpers/docker/elcol_net.py: bafybeia3rzjwwc3isxqnzh6b33lf2m3psuzxj4jlrx7zwomzctxzy6sqoy
  tests/helpers/docker/mock_arblocks_api.py: bafybeid2mp277jhtjnd5piy3eeyc2hghp7mgfu6k2agwohvgi7fvhmhx2a
  tests/helpers/hardhat/Dockerfile: bafybeih7wleg3g263gfsimckqgqb5rtpd72uwm4wzhba2v5u5es5gqhkwy
  tests/helpers/hardhat/hardhat.config.js: bafybeiag3rxhb2luzd4nr6whsti7wtlnvzlm32gctq45p6xfwmsyijpe54
  tests/helpers/hardhat/package.json: bafybeifjyofuzq66sjjtxdynvy4be5rxzkiuwyntjibrjvsrly5ddeai64
  tests/test_agents/__init__.py: bafybeifocm5xbm4nryrzkmzot4bzfnrcnc7nggepgsywterkgw4f44awfi
  tests/test_agents/base_elcollectooorr.py: bafybeidbkjm33eu67lop2hh2oj5sobdut2kdit6fat5bjonjsylxwzx664
  tests/test_agents/test_elcollectooorr_abci.py: bafybeiecsznoutrwxoftf4iu2sesezfxuyzvpyahsv5wnl54hb5xvsp5wa
  tests/test_fractionalize_deployment_abci/__init__.py: bafybeifpwsaub3khxsixvj6yc2b7zlmkpt3h6m2q65x2zmmo6uvcbpdgpm
  tests/test_fractionalize_deployment_abci/test_behaviours.py: bafybeid74vtqghw3uykuufsso5xxtin57v7s4d2p4euxqyiw7q4cop5qqy
  tests/test_fractionalize_deployment_abci/test_dialogues.py: bafybeihea5tjndkyr2a5ezys26mxw3bcrsyrhqdd75egux35ydtvadndva
  tests/test_fractionalize_deployment_abci/test_payloads.py: bafybeidmsyb6ejirhr3o4f7yflxp54mnbhjp64rwbcd2oyu7wcz4pxvsh4
  tests/test_fractionalize_deployment_abci/test_rounds.py: bafybeie673kjeejmeenvy6figj6pdhlhdvtlppxkilrih6ro5viw4chn6q
  tests/test_token_vault/__init__.py: bafybeiav66mysea6p62i7hg4vukzqgxp2khzftxxhjyjlq34fzkjyvbaba
  tests/test_token_vault/test_contract.py: bafybeifbgxr5pclftalkyzz7cyauiq7kqxdvsipacgq65yjuvpry32etjq
  tests/test_token_vault_factory/__init__.py: bafybeibvzzcxfah75gtx6wlvc6k2lfsbwo572bltjxwg2orlv3oqhj5yrq
  tests/test_token_vault_factory/test_contract.py: bafybeibpcizflmxkpi4ik7pnqwxhzjxrin2hret55lvrikigqhv5ptr3dm
fingerprint_ignore_patterns: []
connections:
- valory/abci:0.1.0:bafybeihhidrulgjlrlvmk2c2ax7qmb47ywzjnjqv5gwp7fzzbcgplgaz5a
- valory/http_client:0.23.0:bafybeidykl4elwbcjkqn32wt5h4h7tlpeqovrcq3c5bcplt6nhpznhgczi
- valory/ipfs:0.1.0:bafybeia7kzgw4tmkl6k2vjbnss4egvhcf4fmt7cnmpjjjbjogz2bu2j3fu
- valory/ledger:0.19.0:bafybeiavzloea5rtoxfdqjuexkqzpgbq73n4sl6af2vwa4bv2wd22qigyi
- valory/p2p_libp2p_client:0.1.0:bafybeidwcobzb7ut3efegoedad7jfckvt2n6prcmd4g7xnkm6hp6aafrva
contracts:
- elcollectooorr/artblocks:0.1.0:bafybeify3iw3s4sann3zk6y2ui5nlzg75z374tnngrg35wkdzvrghmbrei
- elcollectooorr/artblocks_minter_filter:0.1.0:bafybeic3wi6v3hkfxmffyu3l7hzr3zh5qbt3jd32gcfzo7pr654ikj4acu
- elcollectooorr/artblocks_periphery:0.1.0:bafybeicdg5eoraievqajkhqa34pl5wsbyrx6mcy2uu5bvt6as74sztfooa
- elcollectooorr/basket:0.1.0:bafybeibp4oinm7k4altxl4r6i5h7uwpgrg7j7bbimxqfyvrjdofv7csxli
- elcollectooorr/basket_factory:0.1.0:bafybeigj3yq2vc3my4f4zmlj6x3zdohgu6k4el626nurb6ddljfthvk4tq
- elcollectooorr/token_vault:0.1.0:bafybeicso2mbwrzzc3cuaupistkbkv4irc6zx2id6d7w7iskozoubey7xi
- elcollectooorr/token_vault_factory:0.1.0:bafybeiab7pdrhybrjh5jfybu4afna6gwtptzme6cui232i7b242liyckhe
- valory/gnosis_safe:0.1.0:bafybeihwwv5aodluykglsbuhhrwusvjof6vvnr37rznwvlutmfwtvoju34
- valory/gnosis_safe_proxy_factory:0.1.0:bafybeieuivicfjkow3asmrj57mygrqbvjnecxqaybyxf6egktdty7qxac4
- valory/multicall2:0.1.0:bafybeiaegx2j5w6le2fhvzmx7stzujuezqfvicvnyqebtipivkek2cgh7m
- valory/multisend:0.1.0:bafybeigjywkl7hydjsrkogob3xebj2ifhqwmfhhxoeyrndzhhxi5u6amey
- valory/service_registry:0.1.0:bafybeickj26svokwax7pf3ytp4lpod646lx3yb5z2bh643xovkoy64ggwi
protocols:
- open_aea/signing:1.0.0:bafybeibqlfmikg5hk4phzak6gqzhpkt6akckx7xppbp53mvwt6r73h7tk4
- valory/abci:0.1.0:bafybeig3dj5jhsowlvg3t73kgobf6xn4nka7rkttakdb2gwsg5bp7rt7q4
- valory/acn:1.1.0:bafybeignmc5uh3vgpuckljcj2tgg7hdqyytkm6m5b6v6mxtazdcvubibva
- valory/contract_api:1.0.0:bafybeidv6wxpjyb2sdyibnmmum45et4zcla6tl63bnol6ztyoqvpl4spmy
- valory/http:1.0.0:bafybeifyoio7nlh5zzyn5yz7krkou56l22to3cwg7gw5v5o3vxwklibhty
- valory/ipfs:0.1.0:bafybeihlgai5pbmkb6mjhvgy4gkql5uvpwvxbpdowczgz4ovxat6vajrq4
- valory/ledger_api:1.0.0:bafybeih6hfzj2obw5oajnt6ng6355edgvi5ngoaub44vpuszqoplfvyaom
- valory/tendermint:0.1.0:bafybeicusvezoqlmyt6iqomcbwaz3xkhk2qf3d56q5zprmj3xdxfy64k54
skills:
- elcollectooorr/elcollectooorr_abci:0.1.0:bafybeiaub675wftxotjbuv3psxipx466v4rzrprt4ibf5i5vpairy475fy
- elcollectooorr/fractionalize_deployment_abci:0.1.0:bafybeic357nobk4yd6ax5iu42lmh6iigxmoyl5cpighgrzyw7m6q2qkqay
- valory/abstract_abci:0.1.0:bafybeiheudaobfaj5lcrqvgwmdysq3za5yjrjtpdiuwhmw5c7lmbgglxti
- valory/abstract_round_abci:0.1.0:bafybeiami2y2uwvtmjf76hl3jvfahujdir5docjby6erdyjl66ekoblesi
- valory/registration_abci:0.1.0:bafybeieaggf6mc43tses5k7fg3pyxca43wsmfvnnzszzucohp5ebg3umwq
- valory/reset_pause_abci:0.1.0:bafybeic6ayed23np6ngkawsf2you6nnfuvbq4smcepdvvcrw5wxn5jaevy
- valory/termination_abci:0.1.0:bafybeigg4eyjaeidojnvxdenztaywb7ijtjdtjirpc6pvhglscfqdhfupe
- valory/transaction_settlement_abci:0.1.0:bafybeiajvxzaeeeamvb3guxtihlrj7xoyrmfeuo5chp4f3pdd2sgiecayq
default_ledger: ethereum
required_ledgers:
- ethereum
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  version: 1
  disable_existing_loggers: false
  formatters:
    standard:
      format: '[%(asctime)s] [%(levelname)s] %(message)s'
  handlers:
    logfile:
      class: logging.FileHandler
      formatter: standard
      filename: ${LOG_FILE:str:log.txt}
      level: INFO
    console:
      class: logging.StreamHandler
      formatter: standard
      stream: ext://sys.stdout
  loggers:
    aea:
      handlers:
      - logfile
      - console
      propagate: false
dependencies:
  open-aea-ledger-ethereum: {}
default_connection: null
---
public_id: valory/abci:0.1.0
type: connection
config:
  target_skill_id: elcollectooorr/elcollectooorr_abci:0.1.0
  host: ${ABCI_HOST:str:localhost}
  port: ${ABCI_PORT:int:26658}
  use_tendermint: ${ABCI_USE_TENDERMINT:bool:false}
---
public_id: valory/p2p_libp2p_client:0.1.0
type: connection
config:
  nodes:
  - uri: ${str:acn.staging.autonolas.tech:9005}
    public_key: ${str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
cert_requests:
- identifier: acn
  ledger_id: ethereum
  message_format: '{public_key}'
  not_after: '2023-01-01'
  not_before: '2022-01-01'
  public_key: ${str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
  save_path: .certs/acn_cosmos_11000.txt
---
public_id: elcollectooorr/elcollectooorr_abci:0.1.0
type: skill
models:
  params:
    args:
      artblocks_contract: '0xa7d8d9ef8D8Ce8992Df33D8b8CF4Aebabd5bD270'
      artblocks_graph_url: https://api.thegraph.com/subgraphs/name/artblocks/art-blocks
      artblocks_minter_filter: '0x4aafce293b9b0fad169c78049a81e400f518e199'
      basket_factory_address: '0xde771104C0C44123d22D39bB716339cD0c3333a1'
      budget_per_vault: 10500000000000000000
      cleanup_history_depth: 1
      consensus:
        max_participants: ${SKILL_ELCOLLECTOOORR_ABCI_MODELS_PARAMS_ARGS_CONSENSUS_MAX_PARTICIPANTS:int:1}
      decision_model_threshold: ${SKILL_ELCOLLECTOOORR_ABCI_MODELS_PARAMS_ARGS_DECISION_MODEL_THRESHOLD:float:0.0}
      setup:
        safe_contract_address: ${SKILL_ELCOLLECTOOORR_ABCI_MODELS_PARAMS_ARGS_SETUP_SAFE_CONTRACT_ADDRESS:list:[]}
      decision_model_type: 'yes'
      drand_public_key: 868f005eb8e6e4ca0a47c8a77ceaa5309a47978a7c71bc5cce96366b5d7a569937c529eeda66c7293784a9402801af31
      enforce_investor_whitelisting: true
      finalize_timeout: 60.0
      history_check_timeout: 1205
      keeper_allowed_retries: 3
      keeper_timeout: 30.0
      max_healthcheck: 120
      max_purchase_per_project: 1
      max_retries: 5
      multisend_address: '0xA238CBeb142c10Ef7Ad8442C6D1f9E89e07e7761'
      observation_interval: 300
      on_chain_service_id: 1
      reset_tendermint_after: 60
      retry_attempts: 400
      retry_timeout: 3
      round_timeout_seconds: 120.0
      service_id: el_collectooorr_1
      multicall_batch_size: ${int:50}
      service_registry_address: ${str:0x48b6af7B12C71f09e2fC8aF4855De4Ff54e775cA}
      settings_address: '0xE0FC79183a22106229B84ECDd55cA017A07eddCa'
      sleep_time: 1
      starting_project_id: 301
      share_tm_config_on_startup: ${bool:false}
      tendermint_check_sleep_delay: 3
      tendermint_max_retries: 5
      tendermint_url: ${TENDERMINT_URL:str:http://localhost:26657}
      tendermint_p2p_url: ${str:localhost:26656}
      tendermint_com_url: ${TENDERMINT_COM_URL:str:http://localhost:8080}
      token_vault_factory_address: '0x85Aa7f78BdB2DE8F3e0c0010d99AD5853fFcfC63'
      validate_timeout: 1205
      wei_to_fraction: 10500000000000000
      whitelisted_investor_addresses: ${SKILL_ELCOLLECTOOORR_ABCI_MODELS_PARAMS_ARGS_WHITELISTED_INVESTOR_ADDRESSES:list:[]}
---
public_id: valory/ledger:0.19.0
type: connection
config:
  ledger_apis:
    ethereum:
      address: ${CONNECTION_LEDGER_CONFIG_LEDGER_APIS_ETHEREUM_ADDRESS:str:http://localhost:8545}
      chain_id: ${CONNECTION_LEDGER_CONFIG_LEDGER_APIS_ETHEREUM_CHAIN_ID:int:31337}
      poa_chain: ${CONNECTION_LEDGER_CONFIG_LEDGER_APIS_ETHEREUM_POA_CHAIN:bool:false}
      default_gas_price_strategy: ${CONNECTION_LEDGER_CONFIG_LEDGER_APIS_ETHEREUM_DEFAULT_GAS_PRICE_STRATEGY:str:eip1559}
