name: elcollectooorr
author: elcollectooorr
version: 0.1.0
description: A set of agents implementing the El Collectooorr
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint:
  README.md: bafybeiheuht3rkoreuimqcyqcdfcp6rjtegvor77xthlb6s2dw5sv4x4uu
fingerprint_ignore_patterns: []
agent: elcollectooorr/elcollectooorr:0.1.0:bafybeietjza4rtzm7b2c2jzx3wxi7kvt4mb5hagtvvo5yoflos4k3xy4y4
number_of_agents: 4
---
public_id: elcollectooorr/elcollectooorr_abci:0.1.0
type: skill
0:
  models:
    params:
      args:
        setup: &id001
          safe_contract_address: ${SAFE_CONTRACT_ADDRESS:list:[]}
        consensus: &id002
          max_participants: 4
        decision_model_threshold: 0.8
        whitelisted_investor_addresses: ${WHITELISTED_INVESTOR_ADDRESSES:list:[]}
        observation_interval: 300
        reset_tendermint_after: 60
        tendermint_p2p_url: ${TM_P2P_ENDPOINT_NODE_0:str:node0:26656}
        service_registry_address: ${SERVICE_REGISTRY_ADDRESS:str:0x48b6af7B12C71f09e2fC8aF4855De4Ff54e775cA}
        on_chain_service_id: ${ON_CHAIN_SERVICE_ID:int:1}
        share_tm_config_on_startup: ${USE_ACN:bool:false}
1:
  models:
    params:
      args:
        setup: *id001
        consensus: *id002
        decision_model_threshold: 0.8
        whitelisted_investor_addresses: ${WHITELISTED_INVESTOR_ADDRESSES:list:[]}
        observation_interval: 300
        reset_tendermint_after: 60
        tendermint_p2p_url: ${TM_P2P_ENDPOINT_NODE_1:str:node1:26666}
        service_registry_address: ${SERVICE_REGISTRY_ADDRESS:str:0x48b6af7B12C71f09e2fC8aF4855De4Ff54e775cA}
        on_chain_service_id: ${ON_CHAIN_SERVICE_ID:int:1}
        share_tm_config_on_startup: ${USE_ACN:bool:false}
2:
  models:
    params:
      args:
        setup: *id001
        consensus: *id002
        decision_model_threshold: 0.8
        whitelisted_investor_addresses: ${WHITELISTED_INVESTOR_ADDRESSES:list:[]}
        observation_interval: 300
        reset_tendermint_after: 60
        tendermint_p2p_url: ${TM_P2P_ENDPOINT_NODE_2:str:node2:26676}
        service_registry_address: ${SERVICE_REGISTRY_ADDRESS:str:0x48b6af7B12C71f09e2fC8aF4855De4Ff54e775cA}
        on_chain_service_id: ${ON_CHAIN_SERVICE_ID:int:1}
        share_tm_config_on_startup: ${USE_ACN:bool:false}
3:
  models:
    params:
      args:
        setup: *id001
        consensus: *id002
        decision_model_threshold: 0.8
        whitelisted_investor_addresses: ${WHITELISTED_INVESTOR_ADDRESSES:list:[]}
        observation_interval: 300
        reset_tendermint_after: 60
        tendermint_p2p_url: ${TM_P2P_ENDPOINT_NODE_3:str:node3:26686}
        service_registry_address: ${SERVICE_REGISTRY_ADDRESS:str:0x48b6af7B12C71f09e2fC8aF4855De4Ff54e775cA}
        on_chain_service_id: ${ON_CHAIN_SERVICE_ID:int:1}
        share_tm_config_on_startup: ${USE_ACN:bool:false}
---
public_id: valory/ledger:0.19.0
type: connection
0:
  config:
    ledger_apis:
      ethereum:
        address: ${SERVICE_ELCOLLECTOOORR_RPC_0:str:http://127.0.0.1:8545}
        chain_id: 1
1:
  config:
    ledger_apis:
      ethereum:
        address: ${SERVICE_ELCOLLECTOOORR_RPC_1:str:http://127.0.0.1:8545}
        chain_id: 1
2:
  config:
    ledger_apis:
      ethereum:
        address: ${SERVICE_ELCOLLECTOOORR_RPC_2:str:http://127.0.0.1:8545}
        chain_id: 1
3:
  config:
    ledger_apis:
      ethereum:
        address: ${SERVICE_ELCOLLECTOOORR_RPC_3:str:http://127.0.0.1:8545}
        chain_id: 1
---
public_id: valory/p2p_libp2p_client:0.1.0
type: connection
config:
  nodes:
  - uri: ${ACN_URI:str:acn.staging.autonolas.tech:9005}
    public_key: ${ACN_NODE_PUBLIC_KEY:str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
cert_requests:
- identifier: acn
  ledger_id: ethereum
  message_format: '{public_key}'
  not_after: '2023-01-01'
  not_before: '2022-01-01'
  public_key: ${ACN_NODE_PUBLIC_KEY:str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
  save_path: .certs/acn_cosmos_11000.txt
