name: elcollectooorr
author: elcollectooorr
version: 0.1.0
description: A set of agents implementing the El Collectooorr
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint:
  README.md: bafybeiheuht3rkoreuimqcyqcdfcp6rjtegvor77xthlb6s2dw5sv4x4uu
fingerprint_ignore_patterns: []
agent: elcollectooorr/elcollectooorr:0.1.0:bafybeibjwmmoaw4smlqy2itaa3bhcpv7p7os3ey2czrvn6m5sjlckkfn2q
number_of_agents: 1
---
public_id: elcollectooorr/elcollectooorr_abci:0.1.0
type: skill
models:
  params:
    args:
      setup:
        safe_contract_address: []
      consensus:
        max_participants: 1
      decision_model_threshold: 0.8
      whitelisted_investor_addresses: []
      observation_interval: 300
      reset_tendermint_after: 60
---
public_id: valory/ledger:0.1.0
type: connection
config:
  ledger_apis:
    ethereum:
      address: https://mainnet.infura.io/v3/API_KEY_HERE
      chain_id: 1
