name: elcollectooorr
author: elcollectooorr
version: 0.1.0
description: A set of agents implementing the El Collectooorr
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint:
  README.md: bafybeiheuht3rkoreuimqcyqcdfcp6rjtegvor77xthlb6s2dw5sv4x4uu
fingerprint_ignore_patterns: []
agent: elcollectooorr/elcollectooorr:0.1.0:bafybeicjpnjcxki4vfhkqh4itiabghzod7w7zdiccdgjg6rwc7snnrgyva
network: polygon
number_of_agents: 1
---
public_id: elcollectooorr/elcollectooorr_abci:0.1.0
type: skill
models:
  params:
    args:
      setup:
        safe_contract_address: []
      consensus:
        max_participants: 1
      decision_model_threshold: 0.0
      whitelisted_investor_addresses:
      - '0xFFcf8FDEE72ac11b5c542428B35EEF5769C409f0'
---
public_id: valory/ledger:0.1.0
type: connection
config:
  ledger_apis:
    ethereum:
      address: https://mainnet.infura.io/v3/1622a5f5b56a4e1f9bd9292db7da93b8
      chain_id: 1
      poa_chain: true
      default_gas_price_strategy: eip1559
