name: elcollectooorr
author: elcollectooorr
version: 0.1.0
description: A set of agents implementing the El Collectooorr
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint:
  README.md: bafybeiheuht3rkoreuimqcyqcdfcp6rjtegvor77xthlb6s2dw5sv4x4uu
fingerprint_ignore_patterns: []
agent: elcollectooorr/elcollectooorr:0.1.0:bafybeihfpj3calvepeh6q6mxb25stci2mchc5uhfxdnowyj7opwb6jewbu
network: ethereum
number_of_agents: 1
---
public_id: elcollectooorr/elcollectooorr_abci:0.1.0
type: skill
models:
  params:
    args:
      setup:
        safe_contract_address: []
      consensus:
        max_participants: 1
      decision_model_threshold: 0.8
      whitelisted_investor_addresses: []
      observation_interval: 180
      reset_tendermint_after: 60
