name: elcollectooorr
author: elcollectooorr
version: 0.1.0
description: A set of agents implementing the El Collectooorr
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint:
  README.md: bafybeiheuht3rkoreuimqcyqcdfcp6rjtegvor77xthlb6s2dw5sv4x4uu
fingerprint_ignore_patterns: []
agent: elcollectooorr/elcollectooorr:0.1.0:bafybeiex6bvoc43y4wnzt2ul4hbgbs44nyypyudrdweapwjrneea2kd7d4
network: ethereum
number_of_agents: 1
---
public_id: elcollectooorr/elcollectooorr_abci:0.1.0
type: skill
models:
  params:
    args:
      setup:
        safe_contract_address:
        - '0xe64C856427C770DEa53E41a0f73C67eE37a16aB4'
      consensus:
        max_participants: 1
      decision_model_threshold: 0.0
      whitelisted_investor_addresses:
      - '0xFFcf8FDEE72ac11b5c542428B35EEF5769C409f0'
