name: elcollectooorr
author: elcollectooorr
version: 0.1.0
description: A set of agents implementing the El Collectooorr
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint:
  README.md: bafybeiheuht3rkoreuimqcyqcdfcp6rjtegvor77xthlb6s2dw5sv4x4uu
fingerprint_ignore_patterns: []
agent: elcollectooorr/elcollectooorr:0.1.0:bafybeiah2absbc7pzuzxuwszr6jrhppu72rf2tfjdbcszdy45hrkmhrata
number_of_agents: 4
---
public_id: elcollectooorr/elcollectooorr_abci:0.1.0
type: skill
models:
  params:
    args:
      setup:
        safe_contract_address: ${SKILL_ELCOLLECTOOORR_ABCI_MODELS_PARAMS_ARGS_SETUP_SAFE_CONTRACT_ADDRESS:list:[]}
      consensus:
        max_participants: 4
      decision_model_threshold: 0.8
      whitelisted_investor_addresses: ${SKILL_ELCOLLECTOOORR_ABCI_MODELS_PARAMS_ARGS_WHITELISTED_INVESTOR_ADDRESSES:list:[]}
      observation_interval: 300
      reset_tendermint_after: 60
---
public_id: valory/ledger:0.19.0
type: connection
config:
  0:
  - ledger_apis:
      ethereum:
        address: ${SERVICE_ELCOLLECTOOORR_RPC_0:str:http://127.0.0.1:8545}
        chain_id: 1
  1:
  - ledger_apis:
      ethereum:
        address: ${SERVICE_ELCOLLECTOOORR_RPC_1:str:http://127.0.0.1:8545}
        chain_id: 1
  2:
  - ledger_apis:
      ethereum:
        address: ${SERVICE_ELCOLLECTOOORR_RPC_2:str:http://127.0.0.1:8545}
        chain_id: 1
  3:
  - ledger_apis:
      ethereum:
        address: ${SERVICE_ELCOLLECTOOORR_RPC_3:str:http://127.0.0.1:8545}
        chain_id: 1
