name: elcollectooorr
author: valory
version: 0.1.0
description: A set of agents implementing the El Collectooorr
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint:
  README.md: bafybeiheuht3rkoreuimqcyqcdfcp6rjtegvor77xthlb6s2dw5sv4x4uu
fingerprint_ignore_patterns: []
agent: valory/elcollectooorr:0.1.0:bafybeieev2ergaatp5iyuv6gwlrjzu36yzynbi27ufqn7yp7up4ozfe27q
network: ethereum
number_of_agents: 1
