agent_name: elcollectooorr
author: valory
version: 0.1.0
license: Apache-2.0
description: El Collectooorr decentralized.
aea_version: '>=1.0.0, <2.0.0'
fingerprint:
  README.md: QmZCpKMCRs4rsbLUeCShw94FXFDoc2DEQKBSgHLeesTfVL
fingerprint_ignore_patterns: []
connections:
- valory/abci:0.1.0:Qme6c15aYEcGog9PCDBydJ65rHmV335qgjDZhcTFEEFyKD
- valory/http_client:0.1.0:QmXiQUWV5AH7BRXGHVxVJpEcLpyNUsZf4pj55FqoTdiGDn
- valory/ledger:0.1.0:Qmc3aNMECkTNTRf5A9vdkmKKxaQQmZb3YBmJxvZNpJNe7j
- valory/p2p_libp2p_client:0.1.0:QmdSWhDzrWBuwz8StPeMan5n2JnuSqg2mayxYMzngQmQfJ
contracts:
- valory/artblocks:0.1.0
- valory/artblocks_periphery:0.1.0
- valory/basket:0.1.0
- valory/basket_factory:0.1.0
- valory/gnosis_safe:0.1.0
- valory/gnosis_safe_proxy_factory:0.1.0
- valory/multisend:0.1.0
- valory/token_vault:0.1.0
- valory/token_vault_factory:0.1.0
protocols:
- open_aea/signing:1.0.0
- valory/abci:0.1.0
- valory/contract_api:1.0.0
- valory/http:1.0.0
- valory/ledger_api:1.0.0
skills:
- valory/abstract_abci:0.1.0
- valory/abstract_round_abci:0.1.0
- valory/elcollectooorr_abci:0.1.0
- valory/fractionalize_deployment_abci:0.1.0
- valory/registration_abci:0.1.0
- valory/safe_deployment_abci:0.1.0
- valory/transaction_settlement_abci:0.1.0
default_ledger: ethereum
required_ledgers:
- ethereum
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  version: 1
  disable_existing_loggers: false
  formatters:
    standard:
      format: '[%(asctime)s] [%(levelname)s] %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: standard
      stream: ext://sys.stdout
  loggers:
    aea:
      handlers:
      - console
      propagate: false
dependencies:
  open-aea-ledger-ethereum: {}
default_connection: null
---
public_id: valory/abci:0.1.0
type: connection
config:
  target_skill_id: valory/elcollectooorr_abci:0.1.0
  use_tendermint: true
---
public_id: valory/p2p_libp2p_client:0.1.0
type: connection
config:
  nodes:
  - uri: ${P2P_URI:str:acn.staging.autonolas.tech:9005}
    public_key: ${P2P_PUBLIC_KEY:str:0250827315351f6f4d3777b77d4bfd67280156240313bf221750b36404344bb35d}
cert_requests:
- identifier: acn
  ledger_id: ethereum
  message_format: '{public_key}'
  not_after: '2022-01-01'
  not_before: '2021-01-01'
  public_key: ${P2P_PUBLIC_KEY:str:0250827315351f6f4d3777b77d4bfd67280156240313bf221750b36404344bb35d}
  save_path: .certs/acn_cosmos_9005.txt
is_abstract: true
